services:
  - type: web
    name: khadis-classroom
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      # On the free plan, disks are not supported. Using local file means data
      # can be lost on redeploy. Upgrade plan or use a managed DB for persistence.
      - key: DB_PATH
        value: ./khadi.db


